In [21]:
import numpy as np

To jest pierwszy notebook w **Datalore** - uczymy się pakietu <span style="color:red;font-size:15pt;">Numpy</span>
<br>
<table>
    <tr><td>Wersja programu</td><td>Data</td></tr>
    <tr><td>1.2</td><td>12.07.2024</td></tr>
</table>

In [22]:
print("komórka testowa!")
t = 45.77
w = 1.89

komórka testowa!


In [23]:
t*w

86.5053

In [24]:
import datetime
dp1 = (datetime.date(2025, 01, 21), datetime.date(2025, 01, 25))

In [25]:
dp1

(datetime.date(2025, 1, 21), datetime.date(2025, 1, 25))

In [26]:
warta = 20

In [27]:
warta*0.2+4.5

8.5

In [28]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.empty(14)

array([5.3714564e-310, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
 0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
 0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
 0.0000000e+000, 0.0000000e+000])

In [30]:
u = np.arange(1,77,3)
u

array([ 1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
 52, 55, 58, 61, 64, 67, 70, 73, 76])

In [31]:
k = np.array([5,3,7,24,89,0,53,2,2])
k

array([ 5, 3, 7, 24, 89, 0, 53, 2, 2])

In [32]:
type(k)

numpy.ndarray

In [33]:
zlista = [4,24,452,34,75,4,6,9,11,3,9,43,1]
print(zlista)
print(type(zlista))

[4, 24, 452, 34, 75, 4, 6, 9, 11, 3, 9, 43, 1]
<class 'list'>


In [35]:
mlista = np.array(zlista)
print(mlista)
print(type(mlista))

[  4  24 452  34  75   4   6   9  11   3   9  43   1]
<class 'numpy.ndarray'>


In [38]:
zlista.sort()
zlista

[1, 3, 4, 4, 6, 9, 9, 11, 24, 34, 43, 75, 452]

In [39]:
mlista.sort()
mlista

array([ 1, 3, 4, 4, 6, 9, 9, 11, 24, 34, 43, 75, 452])

In [40]:
m = np.linspace(0,10,num=5)
m

array([ 0. , 2.5, 5. , 7.5, 10. ])

In [51]:
l1 = [2,4,5,2]
l2 = [78,1,1,1]
l3 = [2,3,98,4]

In [52]:
l = l1+l2+l3
l

[2, 4, 5, 2, 78, 1, 1, 1, 2, 3, 98, 4]

In [53]:
np1 = np.array(l1)
np2 = np.array(l2)
np3 = np.array(l3)

In [54]:
npl = np1+np2+np3

In [55]:
npl

array([ 82, 8, 104, 7])

In [56]:
npkon = np.concatenate((np1,np2,np3))
npkon

array([ 2, 4, 5, 2, 78, 1, 1, 1, 2, 3, 98, 4])

In [57]:
z1 = [[1,3],[4,7]]
z1

[[1, 3], [4, 7]]

In [60]:
z1[1][0]

4

In [61]:
tabnp = np.array([[6,3],[11,7]])
tabnp

array([[ 6, 3],
 [11, 7]])

In [62]:
tabnp[1][1]

7

In [63]:
tabnp[1,1]

7

In [64]:
x = np.array([[2,8],[21,9]])
y = np.array([[15,6],[90,2]])

In [66]:
x

array([[ 2, 8],
 [21, 9]])

In [67]:
y

array([[15, 6],
 [90, 2]])

In [65]:
x+y

array([[ 17, 14],
 [111, 11]])

In [68]:
x-y

array([[-13, 2],
 [-69, 7]])

In [69]:
x*y

array([[ 30, 48],
 [1890, 18]])

In [70]:
x/y

array([[0.13333333, 1.33333333],
 [0.23333333, 4.5 ]])

In [72]:
x%2==0

array([[ True, True],
 [False, False]])

In [75]:
p = np.concatenate((x,y),axis=1)
p

array([[ 2, 8, 15, 6],
 [21, 9, 90, 2]])

In [76]:
p.T

array([[ 2, 21],
 [ 8, 9],
 [15, 90],
 [ 6, 2]])