In [1]:
import numpy as np

In [2]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0, 1, 2, 3, 4],
 [ 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14]])

In [3]:
arr.T

array([[ 0, 5, 10],
 [ 1, 6, 11],
 [ 2, 7, 12],
 [ 3, 8, 13],
 [ 4, 9, 14]])

In [5]:
arr = np.random.randn(6,3)
arr

array([[-0.85242643, -0.06678923, 0.63267998],
 [ 0.09245514, -0.86237251, 1.29871072],
 [-1.40709905, -0.29242317, 0.14138486],
 [-0.29446074, 0.61784343, 0.49026409],
 [-0.86198049, 1.90967939, 0.6993084 ],
 [ 1.68901648, 1.60490743, 0.49833173]])

In [6]:
arr.T

array([[-0.85242643, 0.09245514, -1.40709905, -0.29446074, -0.86198049,
 1.68901648],
 [-0.06678923, -0.86237251, -0.29242317, 0.61784343, 1.90967939,
 1.60490743],
 [ 0.63267998, 1.29871072, 0.14138486, 0.49026409, 0.6993084 ,
 0.49833173]])

In [7]:
np.dot(arr.T,arr)

array([[ 6.39760067, 1.27134858, -0.52364637],
 [ 1.27134858, 7.43799217, 1.23456475],
 [-0.52364637, 1.23456475, 3.0846488 ]])

In [8]:
A = np.array([[1,2],[3,4]])
B = np.array([5,6])

result = np.dot(A,B)
result

#result = [1*5+2*6,3*5+4*6]

array([17, 39])

In [9]:
#tensor3D
tens = np.arange(27).reshape(3,3,3)
tens

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [10]:
tens.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [11]:
tens.transpose(2,0,1)

array([[[ 0,  3,  6],
        [ 9, 12, 15],
        [18, 21, 24]],

       [[ 1,  4,  7],
        [10, 13, 16],
        [19, 22, 25]],

       [[ 2,  5,  8],
        [11, 14, 17],
        [20, 23, 26]]])

In [12]:
tab5D = np.arange(240).reshape((2,2,4,5,3))
tab5D

array([[[[[  0,   1,   2],
          [  3,   4,   5],
          [  6,   7,   8],
          [  9,  10,  11],
          [ 12,  13,  14]],

         [[ 15,  16,  17],
          [ 18,  19,  20],
          [ 21,  22,  23],
          [ 24,  25,  26],
          [ 27,  28,  29]],

         [[ 30,  31,  32],
          [ 33,  34,  35],
          [ 36,  37,  38],
          [ 39,  40,  41],
          [ 42,  43,  44]],

         [[ 45,  46,  47],
          [ 48,  49,  50],
          [ 51,  52,  53],
          [ 54,  55,  56],
          [ 57,  58,  59]]],


        [[[ 60,  61,  62],
          [ 63,  64,  65],
          [ 66,  67,  68],
          [ 69,  70,  71],
          [ 72,  73,  74]],

         [[ 75,  76,  77],
          [ 78,  79,  80],
          [ 81,  82,  83],
          [ 84,  85,  86],
          [ 87,  88,  89]],

         [[ 90,  91,  92],
          [ 93,  94,  95],
          [ 96,  97,  98],
          [ 99, 100, 101],
          [102, 103, 104]],

         [[105, 106, 107],
          [1