In [1]:
import numpy as np

# Część Pierwsza

To jest pierwszy notebook w **Datalore** - uczymy się pakietu <span style="color:red;font-size:15pt;">Numpy</span>
<br>
<table>
    <tr><td>Wersja programu</td><td>Data</td></tr>
    <tr><td>1.2</td><td>12.07.2024</td></tr>
</table>

In [2]:
print("komórka testowa!")
t = 45.77
w = 1.89

komórka testowa!


In [3]:
t*w

86.5053

In [4]:
import datetime
dp1 = (datetime.date(2025, 01, 21), datetime.date(2025, 01, 25))

In [5]:
dp1

(datetime.date(2025, 1, 21), datetime.date(2025, 1, 25))

In [6]:
warta = 20

In [7]:
warta*0.2+4.5

8.5

In [8]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.empty(14)

array([4.87233504e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
 0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
 0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
 0.00000000e+000, 0.00000000e+000])

In [10]:
u = np.arange(1,77,3)
u

array([ 1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
 52, 55, 58, 61, 64, 67, 70, 73, 76])

In [11]:
k = np.array([5,3,7,24,89,0,53,2,2])
k

array([ 5, 3, 7, 24, 89, 0, 53, 2, 2])

In [12]:
type(k)

numpy.ndarray

In [13]:
zlista = [4,24,452,34,75,4,6,9,11,3,9,43,1]
print(zlista)
print(type(zlista))

[4, 24, 452, 34, 75, 4, 6, 9, 11, 3, 9, 43, 1]
<class 'list'>


In [14]:
mlista = np.array(zlista)
print(mlista)
print(type(mlista))

[  4  24 452  34  75   4   6   9  11   3   9  43   1]
<class 'numpy.ndarray'>


In [15]:
zlista.sort()
zlista

[1, 3, 4, 4, 6, 9, 9, 11, 24, 34, 43, 75, 452]

In [16]:
mlista.sort()
mlista

array([ 1, 3, 4, 4, 6, 9, 9, 11, 24, 34, 43, 75, 452])

In [17]:
m = np.linspace(0,10,num=5)
m

array([ 0. , 2.5, 5. , 7.5, 10. ])

In [18]:
l1 = [2,4,5,2]
l2 = [78,1,1,1]
l3 = [2,3,98,4]

In [19]:
l = l1+l2+l3
l

[2, 4, 5, 2, 78, 1, 1, 1, 2, 3, 98, 4]

In [20]:
np1 = np.array(l1)
np2 = np.array(l2)
np3 = np.array(l3)

In [21]:
npl = np1+np2+np3

In [22]:
npl

array([ 82, 8, 104, 7])

In [23]:
npkon = np.concatenate((np1,np2,np3))
npkon

array([ 2, 4, 5, 2, 78, 1, 1, 1, 2, 3, 98, 4])

In [24]:
z1 = [[1,3],[4,7]]
z1

[[1, 3], [4, 7]]

In [25]:
z1[1][0]

4

In [26]:
tabnp = np.array([[6,3],[11,7]])
tabnp

array([[ 6, 3],
 [11, 7]])

In [27]:
tabnp[1][1]

7

In [28]:
tabnp[1,1]

7

In [29]:
x = np.array([[2,8],[21,9]])
y = np.array([[15,6],[90,2]])

In [30]:
x

array([[ 2, 8],
 [21, 9]])

In [31]:
y

array([[15, 6],
 [90, 2]])

In [32]:
x+y

array([[ 17, 14],
 [111, 11]])

In [33]:
x-y

array([[-13, 2],
 [-69, 7]])

In [34]:
x*y

array([[ 30, 48],
 [1890, 18]])

In [35]:
x/y

array([[0.13333333, 1.33333333],
 [0.23333333, 4.5 ]])

In [36]:
x%2==0

array([[ True, True],
 [False, False]])

In [37]:
p = np.concatenate((x,y),axis=1)
p

array([[ 2, 8, 15, 6],
 [21, 9, 90, 2]])

In [38]:
p.T

array([[ 2, 21],
 [ 8, 9],
 [15, 90],
 [ 6, 2]])

# Część Druga

In [41]:
#wektor 12 elementowy
prosta = np.arange(1,13,1)
prosta

array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [42]:
prosta.shape

(12,)

In [49]:
fp = prosta.reshape(3,4)
fp

array([[ 1, 2, 3, 4],
 [ 5, 6, 7, 8],
 [ 9, 10, 11, 12]])

In [50]:
fp.shape

(3, 4)

In [51]:
drugaprosta = fp.reshape(12)
drugaprosta

array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [52]:
mc =np.array([[2,3],[4,8],[11,5]])
mc.shape

(3, 2)

In [53]:
mc

array([[ 2, 3],
 [ 4, 8],
 [11, 5]])

In [54]:
w1 = mc.reshape(6)
w1

array([ 2, 3, 4, 8, 11, 5])

In [70]:
w2 = np.array([5,5.1,2,6,8,2.7,12,34,8])
w12 = np.concatenate((w1,w2))
w12

array([ 2. , 3. , 4. , 8. , 11. , 5. , 5. , 5.1, 2. , 6. , 8. ,
 2.7, 12. , 34. , 8. ])

In [72]:
w12.shape

(15,)

In [74]:
mc15 = w12.reshape(3,5)
mc15

array([[ 2. , 3. , 4. , 8. , 11. ],
 [ 5. , 5. , 5.1, 2. , 6. ],
 [ 8. , 2.7, 12. , 34. , 8. ]])

In [75]:
mc15.dtype

dtype('float64')

In [77]:
mc15 = 2*mc15
mc15

array([[ 4. , 6. , 8. , 16. , 22. ],
 [10. , 10. , 10.2, 4. , 12. ],
 [16. , 5.4, 24. , 68. , 16. ]])

In [78]:
mc15[:2]

array([[ 4. , 6. , 8. , 16. , 22. ],
 [10. , 10. , 10.2, 4. , 12. ]])

In [84]:
#filtorwanie danych wektora w12
start = enumerate(w12)

In [85]:
for i,v in start:
    print(f"{i} -> {v}")

0 -> 2.0
1 -> 3.0
2 -> 4.0
3 -> 8.0
4 -> 11.0
5 -> 5.0
6 -> 5.0
7 -> 5.1
8 -> 2.0
9 -> 6.0
10 -> 8.0
11 -> 2.7
12 -> 12.0
13 -> 34.0
14 -> 8.0


In [86]:
wynik = enumerate(w12[w12<5])
wynik

In [87]:
for i,var in wynik:
    print(f"indeks: {i} -> wartość: {var}")

indeks: 0 -> wartość: 2.0
indeks: 1 -> wartość: 3.0
indeks: 2 -> wartość: 4.0
indeks: 3 -> wartość: 2.0
indeks: 4 -> wartość: 2.7


In [88]:
w12[3:6]

array([ 8., 11., 5.])

In [89]:
pc = (w12>12)
w12[pc]

array([34.])

In [90]:
pv = (w12%2==0)
w12[pv]

array([ 2., 4., 8., 2., 6., 8., 12., 34., 8.])

In [92]:
vb = w12[(w12>2)&(w12<7)]
vb

array([3. , 4. , 5. , 5. , 5.1, 6. , 2.7])

In [93]:
#operacje arytmetyczne na wektorach
wk1 = np.array([1,3,8])
wk2 = np.array([1,1,2])
wk3 = np.array([2,3,2])

In [94]:
wk1-wk2

array([0, 2, 6])

In [95]:
wk1+wk2

array([ 2, 4, 10])

In [96]:
wk1*wk2*wk3

array([ 2, 9, 32])

In [97]:
wk3*1.245

array([2.49 , 3.735, 2.49 ])

In [98]:
np.mean(wk1)

4.0

In [99]:
np.std(wk2)

0.4714045207910317

In [100]:
p90 = np.percentile(wk2,90)
p90

1.8

In [102]:
wk2.min()

1

In [103]:
wk2.max()

2