In [6]:
import numpy as np

In [7]:
# 1. Tworzenie jednowymiarowego wektora za pomocą numpy.array()
wektor = np.array([1, 2, 3, 4, 5])
print("Jednowymiarowy wektor:")
print(wektor)

Jednowymiarowy wektor:
[1 2 3 4 5]


In [8]:
# 2. Tworzenie macierzy dwuwymiarowej za pomocą numpy.array()
macierz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nDwuwymiarowa macierz:")
print(macierz)


Dwuwymiarowa macierz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# 3. Tworzenie macierzy wypełnionej zerami za pomocą numpy.zeros()
macierz_zer = np.zeros((3, 3))
print("\nMacierz wypełniona zerami:")
print(macierz_zer)


Macierz wypełniona zerami:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
# 4. Tworzenie macierzy wypełnionej jedynkami za pomocą numpy.ones()
macierz_jed = np.ones((3, 3))
print("\nMacierz wypełniona jedynkami:")
print(macierz_jed)


Macierz wypełniona jedynkami:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
